Modified navbar styling.
Barnstorm-Research/brc-web pull request #5
Opened 2023-09-08 14:30 UTC by brandondykun

Modified the nav bar to better match the footer design.

2023-09-14 01:25 UTC, RWransky requested changes
Looks great and matches the footer perfectly!

Main need for revision is the code structuring in `Navbar.tsx`. Let me know if you have any questions!

2023-09-14 01:25 UTC, RWransky commented on app/components/Navbar.tsx
> +const HeaderNavLink = ({ href, text }: HeaderNavLinkProps) => {
I'm going to push back a little here with this one... Is the amount of difference between `HeaderNavLink` and `MobileNavLink` enough to justify the reuse of code? I understand the desire to split them into two separate sub-components, but things like `currentRoute`, `isActiveRoute`, and even the base `Link` structure is the same between the two components.

I would advise this instead, even just for the sake of practicing.

Make a generic `NavLink` component. Props are `href`, `text`, `isMobile`, and `onClick?`. `isMobile` is a boolean used within `NavLink` to determine which `className` to use in the `Link` and determines whether or not to use the `onClick` `div`.

With this design we avoid repeating code, while still maintaining the ability to have modular design and functionality. If we thought more than two types of `NavLink`s could exist we would make `isMobile` into `type` and use a switch statement inside the `NavLink` component.

Hopefully that all makes sense!

2023-09-14 16:46 UTC, brandondykun commented
Link components are now refactored into one component. The typing was a little tricky, so if you know a better way to do that I'd be interested in hearing it. The idea is that isMobile and onClick need to be passed together and if either one is passed without the other it will show an error. Now that I write that, that might be redundant. But in our current design, if it's a mobile link, it needs the onClick to close the mobile menu since that doesn't happen automatically. If it's a desktop nav button, there isn't a foreseeable need to attach an onClick, so the typing doesn't allow it. Is this the best way to handle that?

2023-09-15 18:49 UTC, RWransky approved these changes
Thank you for revising the `NavLink` code. Looks perfect!

2023-09-15 18:53 UTC, merged